# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
    - main
  pull_request:
    types: [closed] 
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  name: Vasilev
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      name: Vasil

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, $name!!!
          echo Actor: ${{ github.actor }}
          echo Commited by: ${{ github.event.commits[0].author.name }}

  weather: 
    runs-on: ubuntu-latest
    env: 
#      location: '42.1928,24.3336'
#      lang: en
#      units: metric
#     exclude: 'minutely,hourly,daily,alerts,flags'
      open_weather_map_secret: ${{ secrets.open_weather_map }}
    steps:
      - name: Current weather
      run: curl -s --url "https://api.openweathermap.org/data/2.5/weather?lat=42.1928&lon=24.3336&lang=en&units=metric&exclude=minutely,hourly,daily,alerts,flags&appid=${{ secrets.open_weather_map_secret }}"
      



  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"          

  pull_request_only:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build, test, and deploy your project.
          echo Hi, $name!!!
